# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    
 
    driver: "gd"

    twig:
        mode: lazy

    filter_sets:
        miniature:   
            quality: 85
            filters:
                thumbnail:
                    size: [400, 500]
                    mode: outbound

        portfolio:
            quality: 85
            filters:
                thumbnail:
                    size: [500, 330]
                    mode: outbound

        logo:
            quality: 85
            filters:
                thumbnail:
                    size: [250, 150]
                    mode: outbound
