# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"

    # loaders:
    #     default:
    #         filesystem:
    #             data_root:
    #                 - "%kernel.project_dir%/public"
    #                 - "%kernel.project_dir%/uploads"
    # resolvers:
    #     default:
    #         web_path:
    #             web_root: "%kernel.project_dir%/public"
    #             cache_prefix: media/cache

    # cache: default
 
    driver: "gd"

    filter_sets:
        miniature:   
            quality: 85
            filters:
                thumbnail:
                    size: [400, 500]
                    mode: outbound

        portfolio:
            quality: 85
            filters:
                thumbnail:
                    size: [500, 330]
                    mode: outbound

        logo:
            quality: 85
            filters:
                thumbnail:
                    size: [250, 150]
                    mode: outbound
