vich_uploader:
    db_driver: orm
    metadata:
        type: attribute 

    mappings:
        photo_images:
            uri_prefix: '%photo_images%'
            upload_destination: '%kernel.project_dir%/public%photo_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
